/* Tax Rate */
export const TAX_RATE = 0.1;

/* Art collection */
export const dataArray = [
  {
    id: 1,
    title: 'Digital Art',
    subtitle: 'Exploring the Connection Between Humanity and Technology',
    description: 'Captivating digital artwork inspired by the fusion of humanity and technology.',
    price: 9.99,
    artist: 'ByteBot',
    imageUrl: '/gallery/img/aig_01.jpeg',
  },
  {
    id: 2,
    title: 'Cybernetic Mind',
    subtitle: 'The Evolution of Digital Expression',
    description: 'Discover the beauty of code and creativity in these digital masterpieces.',
    price: 10.99,
    artist: 'Alzmo',
    imageUrl: '/gallery/img/aig_02.jpeg',
  },
  {
    id: 3,
    title: 'Tech Genius',
    subtitle: 'Artificial Intelligence in Modern Society',
    description: 'Explore the depths of the digital realm with these visionary artworks.',
    price: 11.99,
    artist: 'SparkAI',
    imageUrl: '/gallery/img/aig_03.jpeg',
  },
  {
    id: 4,
    title: 'Virtual Reality',
    subtitle: 'The Intersection of Art and Computing',
    description: 'Immerse yourself in a world where art and technology converge.',
    price: 12.99,
    artist: 'Bitzy',
    imageUrl: '/gallery/img/aig_04.jpeg',
  },
  {
    id: 5,
    title: 'Digital Creation',
    subtitle: 'Humans and Machines in Harmony',
    description: 'Witness the symbiotic relationship between humanity and technology through digital art.',
    price: 13.99,
    artist: 'ClankAI',
    imageUrl: '/gallery/img/aig_05.jpeg',
  },
  {
    id: 6,
    title: 'Code Artistry',
    subtitle: 'The Beauty of Algorithms',
    description: 'Experience the elegance of code transformed into captivating visual expressions.',
    price: 14.99,
    artist: 'Wobbletron',
    imageUrl: '/gallery/img/aig_06.jpeg',
  },
  {
    id: 7,
    title: 'Tech Fusion',
    subtitle: 'Humans and Machines Collaborate',
    description: 'Witness the synergy between human creativity and computational power in these artworks.',
    price: 15.99,
    artist: 'ZippAI',
    imageUrl: '/gallery/img/aig_07.jpeg',
  },
  {
    id: 8,
    title: 'Virtual Insights',
    subtitle: 'The Digital Frontier Explored',
    description: 'Embark on a journey through the digital landscape, where imagination knows no bounds.',
    price: 16.99,
    artist: 'Jittrix',
    imageUrl: '/gallery/img/aig_08.jpeg',
  },
  {
    id: 9,
    title: 'Cybernetic Dreams',
    subtitle: 'Visions of a Digital Future',
    description: 'Dive into a world where dreams and technology intertwine to create mesmerizing digital realms.',
    price: 17.99,
    artist: 'DoodlAI',
    imageUrl: '/gallery/img/aig_09.jpeg',
  },
  {
    id: 10,
    title: 'Algorithmic Wonders',
    subtitle: 'The Artistry of Code',
    description: 'Marvel at the artistry embedded within algorithms, transcending the boundaries of traditional art.',
    price: 18.99,
    artist: 'TinkerBot',
    imageUrl: '/gallery/img/aig_10.jpeg',
  },
  {
    id: 11,
    title: 'Digital Realms',
    subtitle: 'Exploring the Boundaries of the Virtual World',
    description: 'Embark on an adventure through digital landscapes, where reality merges with imagination.',
    price: 19.99,
    artist: 'Glitcher',
    imageUrl: '/gallery/img/aig_11.jpeg',
  },
  {
    id: 12,
    title: 'Tech Visions',
    subtitle: 'Envisioning Tomorrow’s World',
    description: 'Peer into the future through the lens of technology, where innovation knows no limits.',
    price: 20.99,
    artist: 'NoodlAI',
    imageUrl: '/gallery/img/aig_12.jpeg',
  },
  {
    id: 13,
    title: 'Digital Odyssey',
    subtitle: 'Journey Through the Digital Age',
    description: 'Embark on an odyssey through the realms of digital art, where creativity knows no bounds.',
    price: 21.99,
    artist: 'BuzzBot',
    imageUrl: '/gallery/img/aig_13.jpeg',
  },
  {
    id: 14,
    title: 'Code Creations',
    subtitle: 'The Artistry of Programming',
    description: 'Witness the creative potential of code, as algorithms transform into visual masterpieces.',
    price: 22.99,
    artist: 'Quirky',
    imageUrl: '/gallery/img/aig_14.jpeg',
  },
  {
    id: 15,
    title: 'Digital Perspectives',
    subtitle: 'New Horizons in Digital Art',
    description: 'Explore innovative perspectives in digital art, where imagination meets technological prowess.',
    price: 23.99,
    artist: 'BlipAI',
    imageUrl: '/gallery/img/aig_15.jpeg',
  },
  {
    id: 16,
    title: 'Tech Horizons',
    subtitle: 'Beyond the Digital Frontier',
    description: 'Peer into the limitless possibilities of technology, where innovation shapes the future.',
    price: 24.99,
    artist: 'Pogobot',
    imageUrl: '/gallery/img/aig_16.jpeg',
  },
];
